#! configuration/base.yaml
application:
  port: 8000
database:
  connection:
    host: "localhost"
    port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "mmasterson@msquaredsolutions.com"
  auth_token: "my-secret-token"
