#! configuration/prod.yaml
application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  # Value retrieved from Postmark's API documentation
  base_url: "https://api.postmark.app"
  # Use the singel sender email you authorised on Postmark!
  sender_email: "mmasterson@msquaredsoftwaresolutions.com"
